// Pure TOML + wrapper-script rendering. Extracted from backend.ts so
// the serialisers are unit-testable without touching the filesystem.

import type { LsfgSettings } from "./types";
import { PROFILE } from "./constants";

/** Minimal TOML basic-string escape — covers backslash and double-quote. */
export function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Render the lsfg-vk TOML config the layer reads at
 * `~/.config/lsfg-vk/conf.toml`. The `[[game]] exe = "..."` profile
 * name is what `LSFG_PROCESS` matches at runtime.
 *
 * The lsfg-vk layer only accepts multipliers >= 2; `0` is our UI-only
 * sentinel for "off" and is enforced by writing a no-op wrapper script
 * (no LSFG_PROCESS export). We still clamp to 2 in the TOML so the
 * layer stays happy for re-enabling later.
 */
export function renderTomlConfig(settings: LsfgSettings, dllPath: string): string {
  const tomlMultiplier = settings.multiplier > 0 ? settings.multiplier : 2;
  return [
    "version = 1",
    "",
    "[global]",
    `current_profile = "${PROFILE}"`,
    `dll = ${tomlString(dllPath)}`,
    `no_fp16 = false`,
    "",
    "[[game]]",
    `exe = "${PROFILE}"`,
    `multiplier = ${tomlMultiplier}`,
    `flow_scale = ${settings.flow_scale}`,
    `performance_mode = ${settings.performance_mode}`,
    `hdr_mode = ${settings.hdr_mode}`,
    `experimental_present_mode = "${settings.experimental_present_mode}"`,
    "",
  ].join("\n");
}

/**
 * Render the `~/lsfg` launch wrapper script.
 *
 * multiplier === 0 means "Off" — emit a passthrough wrapper that does
 * not export LSFG_PROCESS, so the layer's profile match fails and frame
 * generation stays dormant without forcing the user to edit launch
 * options. Flipping multiplier back to 2/3/4 re-arms it.
 */
export function renderWrapperScript(settings: LsfgSettings): string {
  const enabled = settings.multiplier > 0;
  const verbose = settings.verbose_logging;
  const lines = [
    "#!/bin/bash",
    "# lsfg-vk launch wrapper generated by Loadout plugin-lsfg-vk.",
    "# Add to a Steam game's Launch Options as `~/lsfg %command%`.",
    ...(enabled ? [`export LSFG_PROCESS=${PROFILE}`] : []),
    ...(verbose
      ? ["export LSFG_LOG=1", "export VK_LOADER_DEBUG=layer"]
      : []),
    'exec "$@"',
    "",
  ];
  return lines.join("\n");
}
