/**
 * Agent-facing documentation types.
 *
 * Loadout's whole capability surface is already reachable over RPC —
 * `POST /api/rpc` and the `/ws` channel dispatch to any public method on
 * any loaded plugin backend. But `resolveMethod` (see `./plugin`) finds
 * those methods purely by reflection: there is no declared method list,
 * no argument types at runtime, and no descriptions. An AI agent running
 * on a machine with Loadout installed can therefore reach everything and
 * discover nothing.
 *
 * These types describe the missing layer. The shape is deliberately
 * split in two:
 *
 * - {@link AgentDoc} is the **generated baseline** — emitted by
 *   `scripts/generate-agent-docs.ts` from each plugin's `backend.ts`
 *   via the TypeScript compiler API, and written to
 *   `plugins/<id>/agent.json`. It is derived, never hand-edited, and
 *   CI regenerates it to catch drift.
 * - {@link AgentManifest} is the **hand-written curation** — an optional
 *   `agent` block on the plugin manifest (`package.json → plugin.agent`)
 *   carrying the things a type signature cannot express: what a method
 *   is *for*, whether calling it is safe, a worked example, and whether
 *   to hide it from agents entirely.
 *
 * The two are merged at request time (`@loadout/agent-docs`). Curation is
 * therefore incremental: a plugin with no `agent` block still gets useful
 * generated docs, which is what makes ~450 methods across 25 plugins
 * tractable to document at all.
 *
 * Why generated docs live in a sibling `agent.json` rather than on the
 * manifest: `/api/plugins` returns raw `PluginMeta` objects, and the
 * overlay fetches that list on every boot. A per-method schema blob on
 * the manifest would be paid for by every one of those requests. The
 * agent route loads the sibling file lazily instead.
 */

/**
 * How much damage a method can do. Drives whether the agent-facing
 * surface will dispatch a call without an explicit opt-in.
 *
 * - `read` — observes state; safe to call speculatively, safe to poll.
 * - `write` — changes device, Steam or plugin state in a way the user
 *   would notice, but is reversible by calling the obvious inverse.
 * - `destructive` — loses data, interrupts a session, or restarts
 *   something: removing a shortcut, restarting Steam, rebooting.
 *
 * Deliberately no `unknown` member: every method gets a class, so
 * "undocumented" can never render as "no opinion". A method nobody has
 * curated is classified by `inferSafety` in `@loadout/agent-docs` —
 * `read` for unambiguous getter prefixes, `write` for everything else —
 * and flagged {@link AgentMethodDoc.safetyInferred} so a reader can tell
 * a guess from a declaration.
 */
export type AgentSafety = "read" | "write" | "destructive";

/**
 * A JSON-Schema-ish description of one value.
 *
 * This is not a complete JSON Schema implementation and does not try to
 * be: it is generated by lowering TypeScript types, and TypeScript has
 * constructs (conditional types, generics over plugin-local interfaces,
 * function parameters) with no useful JSON Schema equivalent. Rather
 * than fail the build or emit something wrong, the generator falls back
 * to `{ type: "unknown", tsType: "<source text>" }` — an agent reading
 * that at least learns the real signature, which beats a confident lie.
 */
export interface AgentSchema {
  type: "string" | "number" | "boolean" | "null" | "array" | "object" | "unknown";
  /** Present when the generator could not lower the type — the original TypeScript source text. */
  tsType?: string;
  /** For `type: "array"` — the element schema. */
  items?: AgentSchema;
  /** For `type: "object"` — known properties. */
  properties?: Record<string, AgentSchema>;
  /** For `type: "object"` — which of `properties` are required. */
  required?: string[];
  /** Closed set of allowed values, from a TypeScript literal union. */
  enum?: Array<string | number | boolean>;
  /** True when the type included `undefined` / was an optional parameter. */
  optional?: boolean;
  /** True when the type included `null`. */
  nullable?: boolean;
  /** JSDoc text attached to the property, where the generator found any. */
  description?: string;
}

/** One positional argument of an RPC method. */
export interface AgentParam {
  name: string;
  schema: AgentSchema;
  /** Whether the parameter may be omitted (optional or defaulted). */
  optional: boolean;
  /** From the method's JSDoc `@param` tag, where present. */
  description?: string;
}

/**
 * One callable RPC method.
 *
 * `args` is an ordered, positional list because that is what the wire
 * format actually is — `RpcRequest.args` is a `unknown[]` spread into
 * the method (`method(...req.args)`). Presenting it as a named-object
 * schema would read better but would misdescribe the call.
 */
export interface AgentMethodDoc {
  name: string;
  /** Ordered positional arguments. */
  args: AgentParam[];
  /** Schema of the resolved value (promises are unwrapped). */
  returns: AgentSchema;
  /** One-line summary — the method's JSDoc, or curated prose. */
  description?: string;
  safety: AgentSafety;
  /** True when the safety class was inferred rather than declared. */
  safetyInferred?: boolean;
  /** A ready-to-send `args` array demonstrating a realistic call. */
  example?: { args: unknown[] };
  /** Free-form caveats: rate limits, ordering requirements, prerequisites. */
  notes?: string;
}

/** An event a backend emits over the RPC channel via `this.emit(...)`. */
export interface AgentEventDoc {
  event: string;
  description?: string;
  /** Shape of the `data` field, where it could be determined. */
  data?: AgentSchema;
}

/**
 * The generated, on-disk baseline for one plugin —
 * `plugins/<id>/agent.json`. Derived from source; do not hand-edit.
 */
export interface AgentDoc {
  /** Plugin id this documents. Must match the manifest. */
  id: string;
  /**
   * Schema version of this file's own format. Bumped when the generator's
   * output shape changes, so a stale `agent.json` shipped inside an
   * older plugin tree can be detected rather than misread.
   */
  generatorVersion: number;
  methods: AgentMethodDoc[];
  events?: AgentEventDoc[];
}

/** Hand-written curation for a single method, merged over the baseline. */
export interface AgentMethodCuration {
  description?: string;
  safety?: AgentSafety;
  example?: { args: unknown[] };
  notes?: string;
  /**
   * Omit this method from the agent-facing surface entirely. For methods
   * that are public only because another plugin calls them, or that are
   * meaningless outside the plugin's own UI.
   *
   * Note this is a documentation-level hide, not an access control: the
   * method stays callable over `/api/rpc` exactly as before. Anything
   * that must not be called should not be a public backend method.
   */
  hidden?: boolean;
}

/**
 * The optional `agent` block on a plugin manifest
 * (`package.json → plugin.agent`).
 */
export interface AgentManifest {
  /**
   * One or two sentences on what this plugin is for, written for a
   * reader deciding whether it is relevant to the task in front of them.
   * Falls back to the manifest `description` when absent.
   */
  summary?: string;
  /** Per-method curation, keyed by method name. */
  methods?: Record<string, AgentMethodCuration>;
  /**
   * Hide the whole plugin from the agent index. For plugins whose
   * surface is purely decorative (badge injectors, HUD widgets) and
   * would be noise in a capability listing.
   */
  hidden?: boolean;
}

/** One entry in the `/api/agent` index. */
export interface AgentIndexEntry {
  id: string;
  name: string;
  summary: string;
  category?: string;
  /** Loaded plugins are callable; disabled and errored ones are not. */
  status: "loaded" | "disabled" | "error";
  /** How many callable methods it exposes, by safety class. */
  methodCounts: Record<AgentSafety, number>;
  /** Where to fetch the full documentation. */
  href: string;
}
