/**
 * The static `AGENTS.md` discovery file.
 *
 * Deliberately does **not** enumerate capabilities. Only the running
 * loader knows which plugins are enabled on a given machine — the user's
 * `disabledPlugins` config decides that, and a disabled plugin's backend
 * is never even loaded. A static list would go stale the moment someone
 * toggled a plugin, and would be wrong on every machine whose plugin set
 * differs from the repo's.
 *
 * So this file has exactly one job: tell a reader that Loadout is here,
 * and how to ask it what it can do. Everything specific lives behind
 * `GET /api/agent`.
 *
 * Kept as a template function rather than a checked-in literal so the
 * port and route names have a single definition shared with the docs the
 * server itself renders.
 */

/** Loopback origin the loader binds. See `startServer` in the loader. */
export const LOADER_ORIGIN = "http://127.0.0.1:33820";

export function renderAgentsMd(): string {
  return `<!-- Generated by scripts/generate-agent-docs.ts — do not edit by hand. -->

# Loadout — instructions for AI agents

Loadout is a plugin platform for Steam gaming handhelds (Steam Deck,
ROG Ally, Legion Go, OneXPlayer and similar). It runs as a local service
and exposes **everything it can do** over a loopback HTTP API: power and
thermal limits, fan curves, display settings, Bluetooth, WiFi, storage,
Steam library metadata and artwork, game launch options, playtime, and
more — each as a plugin with its own RPC methods.

If you are an agent working on a machine with Loadout installed, you can
drive all of it directly. You do not need to interact with the on-screen
overlay.

## Start here

\`\`\`sh
curl -s ${LOADER_ORIGIN}/api/agent
\`\`\`

That returns an index of the plugins **currently enabled on this
machine**, what each one does, and how to call it. Then fetch a specific
plugin's full method documentation — argument types, return shapes,
safety classes and worked examples:

\`\`\`sh
curl -s ${LOADER_ORIGIN}/api/agent/<plugin-id>
\`\`\`

Both accept \`Accept: application/json\` if you would rather have
structured data than Markdown.

**Do not rely on this file for the capability list.** Which plugins exist
and which are enabled varies per machine and changes when the user
toggles one, so the live endpoint above is the only accurate source.

## Is it running?

\`\`\`sh
curl -s ${LOADER_ORIGIN}/up      # => "ok"
\`\`\`

No response means the service isn't running. It is managed by systemd:

\`\`\`sh
systemctl status loadout
systemctl start loadout
\`\`\`

## Authentication

\`/api/agent\` and the rest of \`/api/*\` are guarded by a session token
that is regenerated every time the service restarts, so fetch it rather
than caching it. The token route itself is public:

\`\`\`sh
TOKEN=$(curl -s ${LOADER_ORIGIN}/api/token | jq -r .token)
curl -s ${LOADER_ORIGIN}/api/agent -H "Authorization: Bearer $TOKEN"
\`\`\`

The service binds \`127.0.0.1\` only and is never reachable off the
machine.

## Calling a method

One endpoint for everything. \`args\` is positional, matching the
signature in the plugin's documentation:

\`\`\`sh
curl -s ${LOADER_ORIGIN}/api/rpc \\
  -H "Authorization: Bearer $TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"plugin":"<plugin-id>","method":"<method>","args":[]}'
\`\`\`

Responses are \`{"id":"…","result":…}\`, or \`{"id":"…","error":"…"}\` with
HTTP 500 when the method threw. Malformed requests return HTTP 400 naming
the problem.

## Before you change anything

Methods are labelled \`read\`, \`write\` or \`destructive\` in the
documentation. Reads are safe to call freely. **Writes on this class of
device are not abstract** — they adjust power limits, fan behaviour and
storage on real hardware the user is holding, and some of them interrupt
a running game.

- Prefer a \`read\` method to confirm current state before changing it.
- Ask the user before calling anything \`write\` or \`destructive\`, unless
  they have already asked you to make that specific change.
- A safety label marked *(inferred)* was guessed from the method name
  rather than declared by the plugin author. Treat those with more care.

Write access through the documented surface is off by default. If the
user wants you to make changes, either send \`X-Loadout-Agent-Write: 1\`
on the request or set \`agentWrites: true\` in
\`~/.config/loadout/config.json\`. This is a guardrail against accidents,
not a security boundary: the token is available to any local process.

## Live events

Plugins push state changes over a WebSocket rather than requiring you to
poll:

\`\`\`
ws://127.0.0.1:33820/ws?token=<token>
\`\`\`

Messages are \`{"type":"event","plugin":"…","event":"…","data":…}\`. Each
plugin's documentation lists the events it emits. \`__core:game-detection\`
emits \`gameChanged\` whenever the running Steam game changes — subscribe
to that rather than polling for the current game.

## Project layout

If you are working on Loadout's own source rather than driving an
installed copy:

| Path | What it is |
| --- | --- |
| \`apps/loadout/\` | The loader — Bun HTTP/WS server, plugin host, Steam CEF injector |
| \`apps/loadout-overlay/\` | The Electrobun (CEF) overlay app |
| \`packages/\` | Shared \`@loadout/*\` workspace libraries |
| \`plugins/<id>/\` | One plugin: \`package.json\` manifest, \`backend.ts\`, \`app.tsx\` |
| \`docs/architecture.md\` | How the pieces fit together |
| \`docs/plugin-development.md\` | Writing a plugin |

\`plugins/<id>/agent.json\` is generated from each backend's TypeScript by
\`scripts/generate-agent-docs.ts\` — edit the source or the \`agent\` block
in the plugin's \`package.json\`, then regenerate. CI fails if they drift.
`;
}
