#!/bin/sh
# Loadout uninstaller script
# Reverses everything done by install.sh, idempotent (safe to run multiple times)
# Usage: curl -fsSL https://raw.githubusercontent.com/srsholmes/loadout/main/scripts/uninstall.sh | sh

set -e

# Configuration
INSTALL_DIR="$HOME/.local/share/loadout"
OVERLAY_INSTALL_DIR="$HOME/.local/share/loadout-overlay"
# Binary path is distro-dependent — must mirror install.sh's branching
# so we remove from the path it was actually written to. See
# docs/install-locations.md. SteamOS: ~/.local/share/loadout/loadout
# (user-writable, no /usr); everywhere else: /usr/local/bin/loadout
# (system path, removal needs sudo).
case "$(. /etc/os-release 2>/dev/null && printf '%s' "${ID:-}")" in
    steamos)
        BINARY_PATH="$INSTALL_DIR/loadout"
        BIN_NEEDS_SUDO=0
        ;;
    *)
        BINARY_PATH="/usr/local/bin/loadout"
        BIN_NEEDS_SUDO=1
        ;;
esac
BIN_LINK="$HOME/.local/bin/loadout"
SERVICE_DIR="$HOME/.config/systemd/user"
# Obsolete per-user backend unit (the backend is now a root system unit).
SERVICE_FILE="$SERVICE_DIR/loadout.service"
SYSTEM_SERVICE_FILE="/etc/systemd/system/loadout.service"
OVERLAY_SERVICE_FILE="$SERVICE_DIR/loadout-overlay.service"
DESKTOP_DIR="$HOME/.local/share/applications"
DESKTOP_FILE="$DESKTOP_DIR/loadout.desktop"
CONFIG_DIR="$HOME/.config/loadout"

# --- InputPlumber wake-button artefacts -------------------------------------
# The overlay wake button is not a Steam setting: the input-plumber plugin
# writes an InputPlumber profile remapping a physical button to KEY_F16 and
# live-loads it over DBus. Removing the backend does NOT undo that, so without
# the revert below the user's button stays bound to F16 after uninstalling and
# stops doing whatever the OS normally does with it (on an OXP Apex, opening
# the on-screen keyboard). See issue #234.
#
# Mirrors the paths in plugins/input-plumber/lib/profile.ts — keep in sync.
IP_ETC_DIR="/etc/loadout/inputplumber"
IP_ETC_PARENT="/etc/loadout"
IP_UACCESS_RULE="/etc/udev/rules.d/71-loadout-inputplumber-uaccess.rules"
IP_DECK_HIDRAW_RULE="/etc/udev/rules.d/72-loadout-deck-hidraw.rules"
# Written only by Loadout versions predating #87 (when the Deck moved to a
# native hidraw watcher). Left in place it keeps InputPlumber claiming the
# Deck's built-in controller away from Steam Input, so it's worth removing —
# but only when it carries our marker, since the path is a general-purpose
# InputPlumber override location a user may have written themselves.
IP_DECK_OVERRIDE="/etc/inputplumber/devices.d/50-steam_deck.yaml"
IP_MARKER="Generated by Loadout"
# The plugin's persisted wake binding (packages/plugin-storage →
# $XDG_CONFIG_HOME/loadout/plugins/<id>.json). The backend runs as root but
# with HOME set to the user's home, so this is the *user's* file. A binding
# recorded here is a stronger signal than the profile on disk: the profile may
# already have been deleted by hand — the #234 workaround starts with
# `rm -rf /etc/loadout` — while the mapping is still live in InputPlumber's
# runtime state and the button is still hijacked.
IP_WAKE_STATE="$CONFIG_DIR/plugins/input-plumber.json"

# Colors (only if terminal supports them)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    RED=''
    GREEN=''
    YELLOW=''
    BLUE=''
    NC=''
fi

info() {
    printf "${BLUE}[INFO]${NC} %s\n" "$1"
}

success() {
    printf "${GREEN}[OK]${NC} %s\n" "$1"
}

warn() {
    printf "${YELLOW}[WARN]${NC} %s\n" "$1"
}

error() {
    printf "${RED}[ERROR]${NC} %s\n" "$1"
}

# Where prompts read from. Under the documented `curl … | sh` uninstall,
# stdin is the script text itself, so `[ -t 0 ]` is false and a bare
# `read` would eat the script rather than the user's answer — the
# plugin-data and config prompts below could never be answered. Read the
# controlling terminal instead. Empty only when there's genuinely no
# terminal (CI, systemd), where prompts fall back to the default (no).
PROMPT_TTY=""
if { true < /dev/tty; } 2>/dev/null; then
    PROMPT_TTY=/dev/tty
fi

# Prompt user for yes/no (defaults to no)
prompt_yn() {
    if [ -z "$PROMPT_TTY" ]; then
        # No terminal to ask on: use default (no)
        return 1
    fi
    printf "%s " "$1" > "$PROMPT_TTY"
    # EOF on the terminal is treated as the default rather than hanging.
    read -r answer < "$PROMPT_TTY" || answer=""
    case "$answer" in
        [Yy]*) return 0 ;;
        *) return 1 ;;
    esac
}

# Run a command as root, skipping the redundant sudo when we already are.
as_root() {
    if [ "$(id -u)" = "0" ]; then
        "$@"
    else
        sudo "$@"
    fi
}

# Reverse the input-plumber plugin's system-level changes: remove the wake
# profile and udev rules we wrote, then restart InputPlumber so the button
# mapping is dropped from its *running* state too.
#
# Deliberately non-destructive about InputPlumber itself. It's the input layer
# the handheld fleet depends on and it predates Loadout on most devices, so we
# never disable or uninstall it — even where Loadout installed it from scratch
# via install-inputplumber.sh. A stock InputPlumber with no Loadout profile
# loaded is exactly the state the device would be in had Loadout never run.
#
# Everything here is best-effort: a failure leaves the user with a working
# system and printed instructions, and must not abort the rest of the
# uninstall (hence the `|| warn` on each privileged step).
revert_inputplumber() {
    ip_found=0
    # Whether any of what we found actually involves InputPlumber. The Deck
    # hidraw rule does NOT: since #87 the Deck wake button is a native hidraw
    # watcher and SteamOS ships InputPlumber disabled or absent, so finding
    # only that rule must not make us talk about InputPlumber at all.
    ip_uses_ip=0
    if [ -e "$IP_ETC_DIR" ]; then
        ip_found=1
        ip_uses_ip=1
    fi
    if [ -f "$IP_UACCESS_RULE" ]; then
        ip_found=1
        ip_uses_ip=1
    fi
    if [ -f "$IP_DECK_HIDRAW_RULE" ]; then ip_found=1; fi
    # Only claim the Deck override if it's ours — the path is a general
    # InputPlumber override location the user may have authored themselves.
    ip_deck_override=0
    if [ -f "$IP_DECK_OVERRIDE" ] && grep -q "$IP_MARKER" "$IP_DECK_OVERRIDE" 2>/dev/null; then
        ip_found=1
        ip_uses_ip=1
        ip_deck_override=1
    fi
    # A persisted non-Deck binding means a mapping may be live in IP even with
    # nothing left on disk, so it has to reach the restart below. Deck bindings
    # ("deck:<button>") never involve InputPlumber — the overlay reads hidraw
    # directly since #87 — so they must not drag IP into this.
    if [ -f "$IP_WAKE_STATE" ] \
        && grep -q '"selectedRaw"[[:space:]]*:[[:space:]]*"' "$IP_WAKE_STATE" 2>/dev/null \
        && ! grep -q '"selectedRaw"[[:space:]]*:[[:space:]]*"deck:' "$IP_WAKE_STATE" 2>/dev/null; then
        ip_found=1
        ip_uses_ip=1
    fi

    if [ "$ip_found" -eq 0 ]; then
        info "No wake-button changes to revert."
        return 0
    fi

    info "Reverting Loadout's wake-button setup (needs sudo)..."
    if [ "$ip_uses_ip" -eq 1 ]; then
        info "InputPlumber itself is left installed and enabled."
    fi

    # Tracked separately because the two rules need different udev triggers to
    # take effect without a replug — mirroring the install side
    # (wake-trigger.ts ensureUaccessRule / wake-trigger-deck.ts
    # ensureDeckHidrawUaccess). Without the trigger the ACLs Loadout granted
    # stay granted until the next reboot.
    ip_removed_input_rule=0
    ip_removed_hidraw_rule=0
    # Tracked so we never report success over a removal that failed.
    ip_remove_failed=0
    if [ -e "$IP_ETC_DIR" ]; then
        if ! as_root rm -rf "$IP_ETC_DIR"; then
            warn "Could not remove $IP_ETC_DIR"
            ip_remove_failed=1
        fi
        # Drop the parent only when empty — never blind-delete /etc/loadout,
        # which other plugins may grow into.
        as_root rmdir "$IP_ETC_PARENT" 2>/dev/null || true
    fi
    if [ -f "$IP_UACCESS_RULE" ]; then
        if as_root rm -f "$IP_UACCESS_RULE"; then
            ip_removed_input_rule=1
        else
            warn "Could not remove $IP_UACCESS_RULE"
            ip_remove_failed=1
        fi
    fi
    if [ -f "$IP_DECK_HIDRAW_RULE" ]; then
        if as_root rm -f "$IP_DECK_HIDRAW_RULE"; then
            ip_removed_hidraw_rule=1
        else
            warn "Could not remove $IP_DECK_HIDRAW_RULE"
            ip_remove_failed=1
        fi
    fi
    if [ "$ip_deck_override" -eq 1 ]; then
        if ! as_root rm -f "$IP_DECK_OVERRIDE"; then
            warn "Could not remove $IP_DECK_OVERRIDE"
            ip_remove_failed=1
        fi
    fi
    if [ "$ip_removed_input_rule" -eq 1 ] || [ "$ip_removed_hidraw_rule" -eq 1 ]; then
        as_root udevadm control --reload 2>/dev/null || true
    fi
    if [ "$ip_removed_input_rule" -eq 1 ]; then
        as_root udevadm trigger --subsystem-match=input 2>/dev/null || true
    fi
    if [ "$ip_removed_hidraw_rule" -eq 1 ]; then
        as_root udevadm trigger --subsystem-match=hidraw --action=change 2>/dev/null || true
    fi

    # The profile lives in InputPlumber's runtime state, loaded over DBus —
    # deleting the file alone doesn't unbind the button until IP rebuilds its
    # composite devices. Restart it so the fix lands now rather than at the
    # next reboot. `reset-failed` first so a previously tripped start-limit
    # can't block the restart (see plugins/input-plumber/lib/wake-trigger.ts).
    #
    # Gated on ip_uses_ip, NOT on the profile file existing: a mapping can be
    # live in IP with the profile already deleted by hand, and gating on the
    # file skipped the restart in exactly that case — leaving the button bound
    # to F16, i.e. #234 unfixed for the users following its own workaround.
    # An unnecessary restart only costs a one-second controller blink, so
    # erring toward restarting is the right trade.
    if [ "$ip_uses_ip" -eq 1 ] && systemctl is-active --quiet inputplumber 2>/dev/null; then
        info "Restarting InputPlumber so the button reverts now (your controller may blink out for a second)..."
        as_root systemctl reset-failed inputplumber 2>/dev/null || true
        if as_root systemctl restart inputplumber; then
            success "Wake button reverted to its default behaviour."
        else
            warn "Could not restart InputPlumber — reboot to finish reverting the button."
        fi
    elif [ "$ip_remove_failed" -eq 0 ]; then
        success "Wake-button files removed."
    fi
    if [ "$ip_remove_failed" -eq 1 ]; then
        warn "Some wake-button files are still on disk — re-run the uninstaller with sudo available."
    fi
}

main() {
    echo ""
    info "========================================="
    info "  Loadout Uninstaller"
    info "========================================="
    echo ""

    # --- Overlay (user service): stop, disable, remove ---
    if systemctl --user is-active loadout-overlay >/dev/null 2>&1; then
        info "Stopping loadout-overlay..."
        systemctl --user stop loadout-overlay || true
    fi
    systemctl --user disable loadout-overlay 2>/dev/null || true
    rm -f "$OVERLAY_SERVICE_FILE"
    # Drop the obsolete per-user backend unit if a prior install left one.
    rm -f "$SERVICE_FILE"
    # `|| true` because there's no user bus to talk to when the script runs
    # without a session (SSH without a pty, a wrapper, `sudo sh`) — under
    # `set -e` a bare daemon-reload would abort the whole uninstall there.
    systemctl --user daemon-reload || true

    # Fallback for when the unit could not be stopped through systemd — no user
    # bus to talk to (SSH without a pty, `sudo sh`), so the `is-active` check
    # above fails and the stop branch is skipped entirely. A surviving overlay
    # process keeps its exclusive EVIOCGRAB on external controllers, so pads
    # look dead in Steam until the user logs out, and the tree gets deleted from
    # under it further down. Matching on the absolute install directory keeps
    # this narrow — nothing else has that path in its command line.
    if command -v pgrep >/dev/null 2>&1 && pgrep -f "$OVERLAY_INSTALL_DIR" >/dev/null 2>&1; then
        info "An overlay process is still running — stopping it so it releases the controller..."
        pkill -TERM -f "$OVERLAY_INSTALL_DIR" 2>/dev/null || true
        # A moment to release the grab and exit cleanly, then insist.
        sleep 1
        if pgrep -f "$OVERLAY_INSTALL_DIR" >/dev/null 2>&1; then
            pkill -KILL -f "$OVERLAY_INSTALL_DIR" 2>/dev/null || true
        fi
    fi
    success "Overlay user service removed."

    # --- Backend (root system service): stop, disable, remove (needs sudo) ---
    # Both privileged steps warn instead of aborting: a declined or mistyped
    # sudo password must not kill the script, because everything below —
    # including the wake-button revert, which is the whole point of #234 —
    # would silently never run.
    if systemctl is-active loadout >/dev/null 2>&1 || [ -f "$SYSTEM_SERVICE_FILE" ]; then
        info "Removing the loadout system service (needs sudo)..."
        sudo systemctl disable --now loadout 2>/dev/null || true
        if sudo rm -f "$SYSTEM_SERVICE_FILE"; then
            sudo systemctl daemon-reload || warn "systemctl daemon-reload failed."
            success "Backend system service removed."
        else
            warn "Could not remove $SYSTEM_SERVICE_FILE — re-run with sudo available."
        fi
    else
        info "Backend system service not installed."
    fi

    # --- Revert the InputPlumber wake button ---
    # After the services are stopped, so the backend can't re-apply the
    # profile between our delete and the InputPlumber restart.
    revert_inputplumber

    # --- Remove .desktop file ---
    if [ -f "$DESKTOP_FILE" ]; then
        info "Removing .desktop file..."
        rm -f "$DESKTOP_FILE"
        success "Desktop file removed."
        # Update desktop database if available
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
        fi
    else
        info "Desktop file not found (already removed)."
    fi

    # --- Remove ~/.local/bin symlink ---
    if [ -L "$BIN_LINK" ]; then
        info "Removing symlink $BIN_LINK..."
        rm -f "$BIN_LINK"
        success "Symlink removed."
    elif [ -f "$BIN_LINK" ]; then
        info "Removing $BIN_LINK..."
        rm -f "$BIN_LINK"
        success "Binary removed from $BIN_LINK."
    else
        info "Symlink $BIN_LINK not found (already removed)."
    fi

    echo ""

    # --- Remove the binary (sudo only when system-owned, per install.sh) ---
    if [ -f "$BINARY_PATH" ]; then
        # Warns rather than aborting, for the same reason as the service
        # removal above: on every non-SteamOS host this is a sudo path, and a
        # declined password used to kill the script here — skipping the plugin
        # data / configuration prompts and the overlay-tree removal, and never
        # printing the final banner, so the user had no idea it stopped early.
        bin_removed=1
        if [ "$BIN_NEEDS_SUDO" = "1" ]; then
            info "Removing $BINARY_PATH (needs sudo)..."
            sudo rm -f "$BINARY_PATH" || bin_removed=0
        else
            info "Removing $BINARY_PATH..."
            rm -f "$BINARY_PATH" || bin_removed=0
        fi
        if [ "$bin_removed" -eq 1 ]; then
            success "Binary removed."
        else
            warn "Could not remove $BINARY_PATH — re-run with sudo available."
        fi
    else
        info "Binary not found at $BINARY_PATH (already removed)."
    fi

    # --- Ask about plugin data ---
    if [ -d "$INSTALL_DIR" ]; then
        if prompt_yn "Remove plugin data at $INSTALL_DIR? (y/N)"; then
            info "Removing plugin data..."
            rm -rf "$INSTALL_DIR"
            success "Removed $INSTALL_DIR"
        else
            info "Plugin data preserved at: $INSTALL_DIR"
        fi
    else
        info "Plugin data directory not found (already removed)."
    fi

    # --- Remove overlay install directory ---
    if [ -d "$OVERLAY_INSTALL_DIR" ]; then
        info "Removing overlay tree at $OVERLAY_INSTALL_DIR..."
        rm -rf "$OVERLAY_INSTALL_DIR"
        success "Overlay removed."
    else
        info "Overlay directory not found (already removed)."
    fi

    # --- Ask about configuration ---
    if [ -d "$CONFIG_DIR" ]; then
        if prompt_yn "Remove configuration? (y/N)"; then
            info "Removing configuration..."
            rm -rf "$CONFIG_DIR"
            success "Configuration removed."
        else
            info "Configuration preserved at: $CONFIG_DIR"
        fi
    else
        info "Configuration directory not found (nothing to remove)."
    fi

    echo ""
    success "========================================="
    success "  Loadout has been uninstalled."
    success "========================================="
    echo ""
}

main
